Models/Category.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Northwind.Models
{
    public class Category
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public ICollection<Product> Products { get; set; }
    }
}

Models/Customer.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Northwind.Models
{
    public class Customer
    {
        public int CustomerId { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
    }
}

Models/Discount.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Northwind.Models
{
    public class Discount
    {
        public int DiscountId { get; set; }
        public int Code { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public int ProductId { get; set; }
        [Column(TypeName = "decimal(4,4)")]
        public decimal DiscountPercent { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

        public Product Product { get; set; }
    }
}

Models/NorthwindContext.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Northwind.Models
{
    public class NorthwindContext : DbContext
    {
        public NorthwindContext(DbContextOptions<NorthwindContext> options) : base(options) { }

        public DbSet<Category> Categories { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Discount> Discounts { get; set; }
        public DbSet<Customer> Customers { get; set; }

        public void AddCustomer(Customer customer)
        {
            this.Add(customer);
            this.SaveChanges();
        }
    }
}

Models/Product.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace Northwind.Models
{
    public class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string QuantityPerUnit { get; set; }
        [Column(TypeName = "decimal(18,4)")]
        public decimal UnitPrice { get; set; }
        public short UnitsInStock { get; set; }
        public short UnitsOnOrder { get; set; }
        public short ReorderLevel { get; set; }
        public bool Discontinued { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

Controllers/DiscountController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Northwind.Models;
using System.Linq;

namespace Northwind.Controllers
{
    public class DiscountController : Controller
    {
        private NorthwindContext _northwindContext;
        public DiscountController(NorthwindContext db) => _northwindContext = db;

        public ActionResult Index() => View(_northwindContext.Discounts.Where(d => d.StartTime <= DateTime.Now && d.EndTime > DateTime.Now));
    }
}

Controllers/HomeController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Northwind.Models;
using System.Linq;

namespace Northwind.Controllers
{
    public class HomeController : Controller
    {
        private NorthwindContext _northwindContext;
        public HomeController(NorthwindContext db) => _northwindContext = db;

        public ActionResult Index() => View(_northwindContext.Discounts.Where(d => d.StartTime <= DateTime.Now && d.EndTime > DateTime.Now).Take(3));
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Northwind.Models;
using System.Linq;

namespace Northwind
{
    public class ProductController : Controller
    {
        private NorthwindContext _northwindContext;
        public ProductController(NorthwindContext db) => _northwindContext = db;

        public IActionResult Category() => View(_northwindContext.Categories.OrderBy(category => category.CategoryName));
        public IActionResult Index(int id) => View(_northwindContext.Products.Where(product => product.CategoryId == id && product.Discontinued == false).OrderBy(product => product.ProductName));
    }
}

Views/Customer/Index.cshtml
@using Northwind.Models
@model IEnumerable<Customer>

<h2 class="mt-3"><i class="fas fa-list-ul"></i>customers</h2>
<a class="btn btn-primary btn-lg active" role="button" asp-action="Register" asp-controller="Customer"><i class="fas fa-users"></i> Register New Customer</a>
<ul class="list-group">
    @foreach (Customer customer in Model)
    {
        <li class="list-group-item list-group-item-action">@customer.CompanyName</li>
    }
</ul>

Views/Customer/Register.cshtml
@model Northwind.Models.Customer

<div class="bg-dark m-1 p-1 text-white"><h4>Register</h4></div>
<form method="post" asp-action="Register">
    <div asp-validation-summary="All"></div>
    <label asp-for="@Model.CompanyName">Enter Company Name</label>
    <input asp-for="@Model.CompanyName" placeholder="Company Name" required minlength="2" maxlength="100"/><br />

    <label asp-for="@Model.Address">Enter Address</label>
    <input asp-for="@Model.Address" placeholder="Address"  minlength="2" maxlength="100"/><br />

    <label asp-for="@Model.City">Enter City</label>
    <input asp-for="@Model.City" placeholder="City"  minlength="2" maxlength="100"/><br />

    <label asp-for="@Model.Region">Enter Region</label>
    <input asp-for="@Model.Region" placeholder="Region"  minlength="2" maxlength="100"/><br />

    <label asp-for="@Model.PostalCode">Enter Postal Code</label>
    <input asp-for="@Model.PostalCode" placeholder="Postal Code"  minlength="2" maxlength="100"/><br />

    <label asp-for="@Model.Country">Enter Country</label>
    <input asp-for="@Model.Country" placeholder="Country"  minlength="2" maxlength="100"/><br />

    <label asp-for="@Model.Phone">Enter Phone</label>
    <input asp-for="@Model.Phone" placeholder="Phone"  minlength="10" maxlength="10"/><br />

    <label asp-for="@Model.Fax">Enter Fax</label>
    <input asp-for="@Model.Fax" placeholder="Fax"  minlength="10" maxlength="10"/><br />

    <button type="submit">Register</button>
</form>

<hr />
<a asp-action="Index">Customer List</a>

Views/Discount/Index.cshtml
@using Northwind.Models
@model IEnumerable<Discount>

<h2 class="mt-3"><i class="fas fa-list-ul"></i>Discounts</h2>
<ul class="list-group">
    @foreach (Discount discount in Model)
    {
        <a class="list-group-item list-group-item-action" asp-action="Index" asp-route-id="@discount.DiscountId">@discount.Title - @discount.Code</a>
    }
</ul>

Views/Home/Index.cshtml
@using Northwind.Models
@model IEnumerable<Discount>

<div class="jumbotron my-2 border border-secondary">
    <h1 class="display-4">Northwind</h1>
    <p class="lead">We have the best prices and selection of high quality foods &amp; beverages on the planet! Check out our featured discounts below.</p>
    <hr class="my-4">
    <p>For exceptional international quisuine, look no further.</p>
    <a class="btn btn-outline-primary btn-lg" href="#" role="button"><i class="fas fa-shopping-cart"></i> Order Now</a>
</div>
<div class="row row-cols-1 row-cols-lg-3">
    @foreach (Discount d in Model)
    {
        <div class="col discounts px-2 py-4">
            <h3>@d.Title</h3>
            <div class="mb-4">
                @d.Description
            </div>
            <i>Discount expires: @d.EndTime.ToString("MM/dd/yyyy")</i><br />
            <a href="#" class="code" data-code="@d.Code" data-product="@d.Title"><i class="far fa-hand-point-right"></i> Discount Code</a>
        </div>
    }
</div>

@section Scripts {
    <script type="text/javascript" src="/js/client.js"></script>
}

Views/Product/Category.cshtml
@using Northwind.Models
@model IEnumerable<Category>

<h2 class="mt-3"><i class="fas fa-list-ul"></i> Product Categories</h2>
<div class="list-group">
    @foreach (Category category in Model)
    {
        <a class="list-group-item list-group-item-action" asp-action="Index" asp-route-id="@category.CategoryId">@category.CategoryName - @category.Description</a>
    }
</div>

Views/Product/Index.cshtml
@using Northwind.Models
@model IEnumerable<Product>

<table class="table table-striped table-borderless">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Product</th>
            <th scope="col" class="text-middle">Price</th>
            <th scope="col" class="text-right">Units In Stock</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Product product in Model)
        {
        <tr>
            <td>@product.ProductName</td>
            <td class="text-middle">@string.Format("{0:c}", product.UnitPrice)</td>
            <td class="text-right">@product.UnitsInStock</td>
        </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>@ViewBag.Title</title>
    <!-- font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <!-- client -->
    <link rel="stylesheet" href="/css/client.css" />
</head>
<body>
    <!-- Toast stuff -->
    <div id="toast" class="toast">
        <div class="toast-header">
            <strong class="mr-auto" id="product"></strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
            Discount Code: <strong id="code"></strong>
        </div>
    </div>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#"><i class="far fa-compass"></i> Northwind</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-database"></i> Products
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" asp-action="Category" asp-controller="Product"><i class="fas fa-list-ul"></i> Browse Categories</a>
                        <a class="dropdown-item" href="#"><i class="fas fa-search"></i> Product Search</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" asp-action="Index" asp-controller="Discount"><i class="fas fa-tag"></i> Current Discounts</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Customer"><i class="fas fa-users"></i> Customers</a>
                </li>
            </ul>
                <form class="form-inline ml-auto d-none d-md-block">
                <input class="form-control mr-sm-2" type="search" placeholder="Search Products" aria-label="Search">
                <button class="btn btn-danger my-2 my-sm-0" type="submit"><i class="fas fa-search"></i><span class="sr-only"> Search</span></button>
            </form>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>